// <auto-generated />
namespace DoulaServices.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DbDoulas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbDoulas));
        
        string IMigrationMetadata.Id
        {
            get { return "201904171349154_DbDoulas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
